dist: trusty
sudo: required

language: php

php:
  - 7.1

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  allow_failures:
    - php: 7.1
    - env: SYMFONY_VERSION=2.8.*

services:
  - neo4j

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)