dist: trusty
sudo: required

language: php

php:
  - 7.1
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.2.*

before_script:
  - wget -O - http://debian.neo4j.org/neotechnology.gpg.key >> key.pgp
  - sudo apt-key add key.pgp
  - echo 'deb http://debian.neo4j.org/repo stable/' | sudo tee -a    - /etc/apt/sources.list.d/neo4j.list > /dev/null
  - sudo apt-get update && sudo apt-get install neo4j
  - sleep 10
  - "curl -H \"Content-Type: application/json\" -X POST -d '{\"password\":\"password\"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password"


install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)