dist: trusty
sudo: required

language: php

php:
  - 7.1

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  allow_failures:
    - php: 7.1
    - env: SYMFONY_VERSION=2.8.*

before_install:
    - sudo apt-get update > /dev/null
    - sh -c ./build/install-jdk8.sh
    - sh -c ./build/install-neo.sh
    - composer self-update
    - travis_retry composer install --prefer-source --no-interaction

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)